name: Close issue with label
on:
  issues:
    types: [labeled]
jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check label
        if: github.event.label.name == '无效/超时'
        run: |
          echo "Issue has the wontfix label. Closing issue."
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"state": "closed"}' \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
