name: Close invalid or stale issues
on:
  schedule:
    - cron: '0 0 * * *' # run once a day
  issues:
    types: [labeled]
jobs:
  close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Filter issues by label
        uses: actions/github-script@v5
        with:
          script: |
            const query = `repo:${context.repo.owner}/${context.repo.repo} is:issue is:open label:"无效/超时"`
            const issues = await github.paginate(github.rest.search.issuesAndPullRequests, { q: query })
            return issues.map(issue => issue.number)
          result-encoding: string
      - name: Close issues
        uses: actions/github-script@v5
        with:
          script: |
            const issue_numbers = JSON.parse(core.getInput('issues'))
            for (const issue_number of issue_numbers) {
              // add a comment before closing the issue
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number,
                body: 'This issue has been closed because it is invalid or stale.'
              })
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number,
                state: 'closed'
              })
            }
          issues: ${{ steps.filter_issues.outputs.result }}
