name: Auto close issues
on:
  issues:
    types: [opened, edited]
jobs:
  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          closed-issues-label: "bug"
          closed-issues-message: "This issue is closed because it does not meet the issue template."

