name: Close invalid or timed out issues
on:
  issues:
    types: [labeled]
jobs:
  close_issue:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'invalid/timed out'
    steps:
      - name: Close issue
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            })
