name: Label issues
on:
  issues:
    types:
      - closed
      - reopened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            if (context.eventName === 'issues' && context.payload.action === 'closed') {
              // issue closed, check the closer and reason
              // same as before
            } else if (context.eventName === 'issues' && context.payload.action === 'reopened') {
              // issue reopened, add label 'reopened'
              github.rest.issues.addLabels (
                {
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ["reopened"]
                })
            }
