name: Close issues with label and comment
on:
  issues:
    types: [labeled]
jobs:
  close_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v2
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            这个issue已经被关闭，因为它被标记为“无效/超时”。
            感谢你的反馈和支持！
      - name: Close issues with label
        uses: bdougie/close-issues-based-on-label@v1.2
        env:
          LABEL: 无效/超时
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
