name: Close issues with label
on:
  schedule:
    - cron: "0 5 * * 3" # every Wednesday at 5am UTC
jobs:
  close_issues_with_label:
    runs-on: ubuntu-latest
    steps:
      - uses: bdougie/close-issues-based-on-label@v1.2
        env:
          LABEL: "bug"
          CLOSE_MESSAGE: "This issue is closed because it is not planned."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
