name: Close issues
on:
  issues:
    types: [labeled]
jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close invalid or completed issues
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = context.issue;
            const label = context.payload.label.name;
            if (label === '无效/超时') {
              await github.issues.createComment({
                issue_number: issue.number,
                owner: issue.owner,
                repo: issue.repo,
                body: '这个issue已经被标记为无效/超时，因此将被关闭。如果你有任何问题或反馈，请重新打开它或创建一个新的issue。谢谢！'
              });
              await github.issues.update({
                issue_number: issue.number,
                owner: issue.owner,
                repo: issue.repo,
                state: 'closed'
              });
            } else if (label === '完成了！') {
              await github.issues.createComment({
                issue_number: issue.number,
                owner: issue.owner,
                repo: issue.repo,
                body: '这个issue已经被标记为完成了！，因此将被关闭。感谢你的贡献和支持！'
              });
              await github.issues.update({
                issue_number: issue.number,
                owner: issue.owner,
                repo: issue.repo,
                state: 'closed'
              });
            }
